# Generated by Django 5.0.4 on 2024-07-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_alter_photometadata_photo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Album",
        ),
    ]
