# Generated by Django 5.0.4 on 2024-07-10 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0003_delete_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photometadata",
            name="photo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="photo.photo",
            ),
        ),
    ]
