# Generated by Django 5.0.4 on 2024-07-10 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("album", "0001_initial"),
        ("photo", "0004_alter_photometadata_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="photos",
            field=models.ManyToManyField(related_name="albums", to="photo.photo"),
        ),
        migrations.AlterField(
            model_name="album",
            name="access_users",
            field=models.ManyToManyField(
                related_name="shared_users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
