# Generated by Django 5.0.4 on 2024-07-10 04:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("album", "0002_album_photos_alter_album_access_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="access_users",
            field=models.ManyToManyField(
                related_name="shared_albums", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
